jobs:
  generate:
    env:
      PRETTIER_CORE_LIB_VERSION: 3.2.5
    name: Create release artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the repository
      uses: actions/checkout@v4
      with:
        path: prettier-java
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - continue-on-error: true
      name: Install tools
      run: 'sudo apt update

        sudo apt install jq

        npm i -g pkg

        '
    - continue-on-error: true
      name: Installing/Linking dependencies
      run: 'cd $GITHUB_WORKSPACE/prettier-java/packages/java-parser

        npm i

        npm link

        cd $GITHUB_WORKSPACE/prettier-java/packages/prettier-plugin-java

        npm i

        npm link java-parser

        '
    - continue-on-error: true
      name: Checkout Prettier
      uses: actions/checkout@v2
      with:
        path: prettier
        ref: refs/tags/${{ env.PRETTIER_CORE_LIB_VERSION }}
        repository: prettier/prettier
    - continue-on-error: true
      name: Link Prettier-java to Prettier
      run: 'cd $GITHUB_WORKSPACE/prettier

        npm i

        npm link prettier-plugin-java

        mv package.json package.json.old

        jq ''.dependencies["prettier-plugin-java"] = "./node_modules/prettier-plugin-java"''
        package.json.old | cat > package.json

        '
    - continue-on-error: true
      name: Build the artifacts
      run: 'cd $GITHUB_WORKSPACE/prettier

        pkg package.json -o $GITHUB_WORKSPACE/prettier-java-${GITHUB_REF##*/} --targets
        node10-linux-x64,node10-macos-x64,node10-win-x64

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      with:
        args: prettier-java-*
name: Binary artifacts
on:
  repository_dispatch:
    types: trigger-ga___binaries.yml
