jobs:
  build:
    if: github.repository == 'jhipster/prettier-java'
    name: copyright update
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
    - continue-on-error: true
      name: Find and Replace
      run: 'CURRENT_YEAR=$(date +''%Y'')

        NEW_YEAR=$(($CURRENT_YEAR + 1))

        grep -rlZE "Copyright ([0-9]+)-$CURRENT_YEAR" . | xargs -0 sed -i -E "s/Copyright
        ([0-9]+)-$CURRENT_YEAR/Copyright \1-$NEW_YEAR/g"

        '
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        author: jhipster-bot <jhipster-bot@users.noreply.github.com>
        body: This is an automated pull request to update the copyright headers
        branch: copyright-date-update
        commit-message: Update copyright headers
        title: Update Copyright Headers
        token: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 40
name: Copyright Update
on:
  repository_dispatch:
    types: trigger-ga___copyright-update.yml
permissions:
  contents: read
